version: "3.9"
services:
  relay_transport_rabbitmq1:
    image: tt-relay-rabbit
    build:
      context: ./rabbitmq/
    container_name: relay_transport_rabbitmq1
    hostname: relay_transport_rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - relay_transport_rabbitmq.env
    networks:
      - relayserver
  relay_transport_rabbitmq2:
    image: tt-relay-rabbit
    container_name: relay_transport_rabbitmq2
    hostname: relay_transport_rabbitmq2
    links:
      - relay_transport_rabbitmq1
    ports:
      - "5673:5672"
      - "15673:15672"
    env_file:
      - relay_transport_rabbitmq.env
      - relay_transport_rabbitmq2.env
    depends_on:
      - relay_transport_rabbitmq1
    networks:
      - relayserver
  relay_logging_seq:
    image: datalust/seq:latest
    container_name: relay_logging_seq
    hostname: relay_logging_seq
    ports:
      - "5341:80"
    env_file:
      - relay_logging_seq.env
    volumes:
      - seq-data:/data
    networks:
      - relayserver
  relay_persistence_postgresql:
    image: postgres:15-alpine
    container_name: relay_persistence_postgresql
    hostname: relay_persistence_postgresql
    ports:
      - "5432:5432"
    env_file:
      - relay_persistence_postgresql.env
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - relayserver
  relay_server_migrations:
    image: relay_server
    build:
      context: ..
      dockerfile: ./docker/Thinktecture.Relay.Server.Docker/Dockerfile
    container_name: relay_server_migrations
    hostname: relay_server_migrations
    depends_on:
      - relay_transport_rabbitmq1
      - relay_transport_rabbitmq2
      - relay_persistence_postgresql
    networks:
      - relayserver
    entrypoint: ["dotnet", "Thinktecture.Relay.Server.Docker.dll", "migrate-only=true"]
  relay_management:
    image: relay_management
    build:
      context: ..
      dockerfile: ./docker/Thinktecture.Relay.ManagementApi.Docker/Dockerfile
    container_name: relay_management
    hostname: relay_management
    privileged: false
    ports:
      - "5004:5000"
    env_file:
      - relay_management.env
    depends_on:
      - relay_logging_seq
      - relay_persistence_postgresql
      - relay_server_migrations
    networks:
      - relayserver
volumes:
  seq-data:
    driver: local
  postgresql-data:
    driver: local
networks:
  relayserver:
    driver: bridge
    name: relayserver
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
