// <auto-generated />
namespace Thinktecture.Relay.Server.Migrations
{
	using System.CodeDom.Compiler;
	using System.Data.Entity.Migrations;
	using System.Data.Entity.Migrations.Infrastructure;
	using System.Resources;

	[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
	public sealed partial class AddActiveConnectionsTable : IMigrationMetadata
	{
		private readonly ResourceManager Resources = new ResourceManager(typeof(AddActiveConnectionsTable));

		string IMigrationMetadata.Id
		{
			get { return "201707240650482_AddActiveConnectionsTable"; }
		}

		string IMigrationMetadata.Source
		{
			get { return null; }
		}

		string IMigrationMetadata.Target
		{
			get { return Resources.GetString("Target"); }
		}
	}
}
